column_name_changes = { 'Shots / on target' : 'Shots',
'Unnamed: 9' : 'Shots on Target',
'Unnamed: 10' : 'Shot Accuracy',
'Passes / accurate' : 'Passes',
'Unnamed: 12' : 'Passes on Target',
'Unnamed: 13' : 'Pass Accuracy',
'Losses / Low / Medium / High' : 'Losses',
'Unnamed: 16' : 'Low Losses', 
'Unnamed: 17' : 'Medium Losses', 
'Unnamed: 18' : 'High Losses', 
'Recoveries / Low / Medium / High' : 'Recoveries', 
'Unnamed: 20' : 'Low Recoveries', 
'Unnamed: 21' : 'Medium Recoveries', 
'Unnamed: 22' : 'High Recoveries', 
'Duels / won' : 'Duels',
'Unnamed: 24' : 'Duels won',
'Unnamed: 25' : 'Duel win %',
'Shots from outside penalty area / on target' : 'Shots from outside',
'Unnamed: 27' : 'Shots from outside on target',
'Unnamed: 28' : 'Shots from outside accuracy',
'Positional attacks / with shots' : 'Positional attacks',
'Unnamed: 30' : 'Positional attacks with shots',
'Unnamed: 31' : 'Positional attacks with shots %',
'Counterattacks / with shots' : 'Counterattacks',
'Unnamed: 33' : 'Counterattacks with shots',
'Unnamed: 34' : 'Counterattacks with shots %',
'Set pieces / with shots' : 'Set pieces',
'Unnamed: 36' : 'Set pieces with shots',
'Unnamed: 37' : 'Set pieces with shots %',
'Corners / with shots' : 'Corners',
'Unnamed: 39' : 'Corners with shots',
'Unnamed: 40' : 'Corners with shots %',
'Free kicks / with shots' : 'Free kicks',
'Unnamed: 42' : 'Free kicks with shots',
'Unnamed: 43' : 'Free kicks with shots %',
'Penalties / converted' : 'Penalties',
'Unnamed: 45' : 'Penalties converted',
'Unnamed: 46' : 'Penalties converted %',
'Crosses / accurate' : 'Crosses',
'Unnamed: 48' : 'Crosses accurate',
'Unnamed: 49' : 'Crosses accurate %',
'Penalty area entries / (runs / crosses)' : 'Penalty area entries total',
'Unnamed: 53' : 'Penalty area entries runs',
'Unnamed: 54' : 'Penalty area entries crosses',
'Offensive duels / won' : 'Offensive duels',
'Unnamed: 57' : 'Offensive duels won',
'Unnamed: 58' : 'Offensive duels won %',
'Shots against / on target' : 'Shots against',
'Unnamed: 62' : 'Shots against on target',
'Unnamed: 63' : 'Shots against on target %',
'Defensive duels / won' : 'Defensive duels',
'Unnamed: 65' : 'Defensive duels won',
'Unnamed: 66' : 'Defensive duels won %',
'Aerial duels / won' : 'Aerial duels',
'Unnamed: 68' : 'Aerial duels won',
'Unnamed: 69' : 'Aerial duels won %',
'Sliding tackles / successful' : 'Sliding tackles',
'Unnamed: 71' : 'Sliding tackles successful',
'Unnamed: 72' : 'Sliding tackles successful %',
'Forward passes / accurate' : 'Forward passes',
'Unnamed: 79' : 'Forward passes accurate',
'Unnamed: 80' : 'Forward passes accurate %',
'Back passes / accurate' : 'Back passes',
'Unnamed: 82' : 'Back passes accurate',
'Unnamed: 83' : 'Back passes accurate %',
'Lateral passes / accurate' : 'Lateral passes',
'Unnamed: 85' : 'Lateral passes accurate',
'Unnamed: 86' : 'Lateral passes accurate %',
'Long passes / accurate' : 'Long passes',
'Unnamed: 88' : 'Long passes accurate',
'Unnamed: 89' : 'Long passes accurate %',
'Passes to final third / accurate' : 'Passes to final third',
'Unnamed: 91' : 'Passes to final third accurate',
'Unnamed: 92' : 'Passes to final third accurate %',
'Progressive passes / accurate' : 'Progressive passes',
'Unnamed: 94' : 'Progressive passes accurate',
'Unnamed: 95' : 'Progressive passes accurate %',
'Smart passes / accurate' : 'Smart passes',
'Unnamed: 97' : 'Smart passes accurate',
'Unnamed: 98' : 'Smart passes accurate %',
'Throw ins / accurate' : 'Throw ins',
'Unnamed: 100' : 'Throw ins accurate',
'Unnamed: 101' : 'Throw ins accurate %',
}